### ISSUE TITLE
error if new colujmn in table isn't in first item of DB

### ISSUE THREAD

**Issue by hunterowens** [simonw/yaml-to-sqlite#4]
Hi - 

I was modifying the [following file](https://github.com/hunterowens/gardenbot/blob/main/seeds.yml) by adding a key, `need_to_reorder` in one of the fields. I was unable to add it to the DB unless I added it inside the first column. 

I solved this via a workaround in my github workflow of nuking the DB, but won't be appropriate for datasets with long build times I think

**Comment by simonw** [comment]
Thanks for the catch - adding `alter=True` should fix this. I'll take a look tomorrow.
